CREATE TABLE TB_PRODUTO (
  ID_PRODUTO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO PRIMARY KEY, 
  NM_PRODUTO VARCHAR(100) NOT NULL,
  DS_PRODUTO VARCHAR(1000) NOT NULL,
  DT_CADASTRO TIMESTAMP NOT NULL,
  VL_PRODUTO DECIMAL(12,2) NOT NULL
);

CREATE TABLE TB_IMAGEM (
  ID_IMAGEM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_IMAGEM PRIMARY KEY,
  NM_IMAGEM VARCHAR(100) NOT NULL,
  DS_IMAGEM VARCHAR(100),
  ID_PRODUTO BIGINT NOT NULL
);

ALTER TABLE TB_IMAGEM ADD CONSTRAINT FK_PRODUTO_IMAGEM FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

CREATE TABLE TB_CATEGORIA (
  ID_CATEGORIA INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CATEGORIA PRIMARY KEY,
  NM_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE TB_PRODUTO_CATEGORIA (
  ID_PRODUTO BIGINT NOT NULL,
  ID_CATEGORIA INT NOT NULL
);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);
