INSERT INTO TB_CATEGORIA (NM_CATEGORIA) VALUES
('Bolo'),
('Torta'),
('Chocolate'),
('Morango'),
('Abacaxi'),
('Coco'),
('Cenoura'),
('Frutas'),
('Crocante'),
('Light');

INSERT INTO TB_PRODUTO (NM_PRODUTO, DS_PRODUTO, DT_CADASTRO, VL_PRODUTO) VALUES
('Bolo de chocolate', 'Melhor bolo de chocolate do mundo', CURRENT_TIMESTAMP, 100.00),
('Torta crocante', 'Torta para todas as horas', CURRENT_TIMESTAMP, 120.00),
('Bolo de cenoura', 'Este é O BOLO!!!', CURRENT_TIMESTAMP, 90.00),
('Bolo light', 'Bolo de frutas porque gordice para quem não quer ganhar peso', CURRENT_TIMESTAMP, 150.00),
('Floresta negra', 'Muito chocolate', CURRENT_TIMESTAMP, 110.00),
('Torta de morango', 'Muito morango e muita torta', CURRENT_TIMESTAMP, 95.00),
('Sonho de valsa', 'Bolo sonho de valsa', CURRENT_TIMESTAMP, 95.00),
('Morango com leite condensado', 'Bolo muito recheado', CURRENT_TIMESTAMP, 150.00),
('Abacaxi com coco', 'Bolo para quem gosta de frutas', CURRENT_TIMESTAMP, 125.00),
('Mega Choco', 'Bolo para quem curte MUITO CHOCOLATE', CURRENT_TIMESTAMP, 160.00);

INSERT INTO TB_IMAGEM (NM_IMAGEM, DS_IMAGEM, ID_PRODUTO) VALUES 
('bolo.jpg', 'Imagem do bolo 1', 1),
('bolo2.jpg', 'Imagem do bolo 2', 1),
('bolo3.jpg', 'Imagem do bolo 3', 1),
('bolo4.jpg', 'Imagem do bolo 4', 1),
('bolo.jpg', 'Imagem do bolo', 2),
('bolo2.jpg', 'Imagem do bolo', 3),
('bolo3.jpg', 'Imagem do bolo', 4),
('bolo4.jpg', 'Imagem do bolo', 5),
('bolo.jpg', 'Imagem do bolo', 6),
('bolo2.jpg', 'Imagem do bolo', 7),
('bolo3.jpg', 'Imagem do bolo', 8),
('bolo4.jpg', 'Imagem do bolo', 9),
('bolo.jpg', 'Imagem do bolo', 10);

INSERT INTO TB_PRODUTO_CATEGORIA (ID_PRODUTO, ID_CATEGORIA) VALUES 
(1, 1),
(1, 3),
(2, 2),
(2, 10),
(3, 1),
(3, 7),
(3, 10),
(4, 1),
(4, 8),
(4, 10),
(5, 1),
(5, 3),
(6, 2),
(6, 4),
(7, 1),
(7, 3),
(7, 9),
(8, 1),
(8, 4),
(9, 1),
(9, 5),
(9, 6),
(9, 10),
(10, 1),
(10, 3);